import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import {
  scaffoldItems,
  ALL_WIZARD_ITEMS,
  WIZARD_CHOICES,
} from "../wizard";
import type { WizardItem } from "../wizard";
import { generateHooksTemplate, HOOKS_HEADER } from "../../../templates/claude-code/hooks";
import { generateSkillTemplates } from "../../../templates/claude-code/skills";
import { generateAgentTemplates } from "../../../templates/claude-code/agents";

function makeTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "mnotes-wizard-test-"));
}

function cleanTmpDir(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

const DEFAULT_OPTS = {
  url: "http://localhost:3000",
  workspaceId: "ws-test-123",
};

// =============================================================
// T-1: Template generation — hooks
// =============================================================
describe("hooks template", () => {
  it("generates SessionStart hook with correct URL and workspaceId", () => {
    const hooks = generateHooksTemplate(DEFAULT_OPTS);
    expect(hooks.SessionStart).toBeDefined();
    expect(hooks.SessionStart).toHaveLength(1);
    expect(hooks.SessionStart![0].type).toBe("command");
    expect(hooks.SessionStart![0].command).toContain("localhost:3000");
    expect(hooks.SessionStart![0].command).toContain("ws-test-123");
  });

  it("strips trailing slashes from URL", () => {
    const hooks = generateHooksTemplate({ url: "http://example.com///", workspaceId: "ws-1" });
    expect(hooks.SessionStart![0].command).toContain("http://example.com/api/mcp");
    expect(hooks.SessionStart![0].command).not.toContain("///");
  });
});

// =============================================================
// T-1: Template generation — skills
// =============================================================
describe("skills templates", () => {
  it("generates two skill files", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    expect(skills).toHaveLength(2);
  });

  it("generates store and recall skills", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    const filenames = skills.map((s) => s.filename);
    expect(filenames).toContain("mnotes-store.md");
    expect(filenames).toContain("mnotes-recall.md");
  });

  it("includes m-notes generated header (AC-8)", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("Generated by m-notes CLI");
    }
  });

  it("includes workspaceId in skill content", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("ws-test-123");
    }
  });

  it("includes frontmatter with name and trigger", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("---");
      expect(skill.content).toContain("name:");
      expect(skill.content).toContain("trigger:");
    }
  });
});

// =============================================================
// T-1: Template generation — agents
// =============================================================
describe("agents templates", () => {
  it("generates one agent file", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents).toHaveLength(1);
  });

  it("generates knowledge-manager agent", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].filename).toBe("knowledge-manager.md");
  });

  it("includes m-notes generated header (AC-8)", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    for (const agent of agents) {
      expect(agent.content).toContain("Generated by m-notes CLI");
    }
  });

  it("includes workspaceId in agent content", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].content).toContain("ws-test-123");
  });

  it("includes frontmatter with name and description", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].content).toContain("---");
    expect(agents[0].content).toContain("name: knowledge-manager");
    expect(agents[0].content).toContain("description:");
  });
});

// =============================================================
// T-2: Wizard choices structure
// =============================================================
describe("wizard choices", () => {
  it("has three items: hooks, skills, agents", () => {
    expect(ALL_WIZARD_ITEMS).toEqual(["hooks", "skills", "agents"]);
  });

  it("each choice has value, label, and description", () => {
    for (const choice of WIZARD_CHOICES) {
      expect(choice.value).toBeTruthy();
      expect(choice.label).toBeTruthy();
      expect(choice.description).toBeTruthy();
    }
  });
});

// =============================================================
// T-3: scaffoldItems — hooks
// =============================================================
describe("scaffoldItems: hooks", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("creates .claude/settings.json with hooks (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("hooks");
    expect(results[0].filesWritten).toHaveLength(1);

    const settingsPath = path.join(tmpDir, ".claude", "settings.json");
    expect(fs.existsSync(settingsPath)).toBe(true);

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    expect(settings.hooks).toBeDefined();
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(settings.hooks.SessionStart).toHaveLength(1);
  });

  it("merges hooks into existing settings.json (AC-5)", () => {
    const claudeDir = path.join(tmpDir, ".claude");
    fs.mkdirSync(claudeDir, { recursive: true });

    const existingSettings = {
      permissions: { allow: ["Read"] },
      hooks: {
        PreToolUse: [{ type: "command", command: "echo pre-tool" }],
      },
    };
    fs.writeFileSync(
      path.join(claudeDir, "settings.json"),
      JSON.stringify(existingSettings, null, 2),
      "utf-8"
    );

    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);

    const settings = JSON.parse(
      fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8")
    );

    // Existing settings preserved
    expect(settings.permissions.allow).toEqual(["Read"]);
    // Existing hooks preserved
    expect(settings.hooks.PreToolUse).toHaveLength(1);
    expect(settings.hooks.PreToolUse[0].command).toBe("echo pre-tool");
    // New hooks added
    expect(settings.hooks.SessionStart).toHaveLength(1);
  });

  it("does not duplicate hooks on re-run (AC-5)", () => {
    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);
    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);

    const settings = JSON.parse(
      fs.readFileSync(path.join(tmpDir, ".claude", "settings.json"), "utf-8")
    );

    expect(settings.hooks.SessionStart).toHaveLength(1);
  });
});

// =============================================================
// T-3: scaffoldItems — skills
// =============================================================
describe("scaffoldItems: skills", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("creates skill files in .claude/skills/ (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("skills");
    expect(results[0].filesWritten.length).toBeGreaterThan(0);

    const skillsDir = path.join(tmpDir, ".claude", "skills");
    expect(fs.existsSync(path.join(skillsDir, "mnotes-store.md"))).toBe(true);
    expect(fs.existsSync(path.join(skillsDir, "mnotes-recall.md"))).toBe(true);
  });

  it("generated skill files include header (AC-8)", () => {
    scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    const storeContent = fs.readFileSync(
      path.join(tmpDir, ".claude", "skills", "mnotes-store.md"),
      "utf-8"
    );
    expect(storeContent).toContain("Generated by m-notes CLI");
  });

  it("preserves user-created skill files (AC-5)", () => {
    const skillsDir = path.join(tmpDir, ".claude", "skills");
    fs.mkdirSync(skillsDir, { recursive: true });

    // Write a user-created file with the same name
    fs.writeFileSync(
      path.join(skillsDir, "mnotes-store.md"),
      "# My custom store skill\nCustom content here",
      "utf-8"
    );

    const results = scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    // The user file should be preserved
    const content = fs.readFileSync(
      path.join(skillsDir, "mnotes-store.md"),
      "utf-8"
    );
    expect(content).toContain("My custom store skill");
    expect(content).not.toContain("Generated by m-notes CLI");

    // The recall skill should still be written (new file)
    expect(fs.existsSync(path.join(skillsDir, "mnotes-recall.md"))).toBe(true);
  });

  it("overwrites m-notes generated skill files on re-run (AC-5)", () => {
    scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    // Re-run with different workspaceId
    scaffoldItems(tmpDir, ["skills"], { url: "http://new-url.com", workspaceId: "ws-new" });

    const content = fs.readFileSync(
      path.join(tmpDir, ".claude", "skills", "mnotes-store.md"),
      "utf-8"
    );
    expect(content).toContain("ws-new");
  });
});

// =============================================================
// T-3: scaffoldItems — agents
// =============================================================
describe("scaffoldItems: agents", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("creates agent files in .claude/agents/ (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("agents");
    expect(results[0].filesWritten.length).toBeGreaterThan(0);

    expect(
      fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))
    ).toBe(true);
  });

  it("generated agent files include header (AC-8)", () => {
    scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);

    const content = fs.readFileSync(
      path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"),
      "utf-8"
    );
    expect(content).toContain("Generated by m-notes CLI");
  });

  it("preserves user-created agent files (AC-5)", () => {
    const agentsDir = path.join(tmpDir, ".claude", "agents");
    fs.mkdirSync(agentsDir, { recursive: true });

    fs.writeFileSync(
      path.join(agentsDir, "knowledge-manager.md"),
      "# My custom agent\nCustom agent content",
      "utf-8"
    );

    scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);

    const content = fs.readFileSync(
      path.join(agentsDir, "knowledge-manager.md"),
      "utf-8"
    );
    expect(content).toContain("My custom agent");
  });
});

// =============================================================
// T-3: scaffoldItems — all items at once
// =============================================================
describe("scaffoldItems: all items", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("scaffolds hooks, skills, and agents when all selected (AC-7)", () => {
    const results = scaffoldItems(tmpDir, ALL_WIZARD_ITEMS, DEFAULT_OPTS);
    expect(results).toHaveLength(3);

    const items = results.map((r) => r.item);
    expect(items).toContain("hooks");
    expect(items).toContain("skills");
    expect(items).toContain("agents");

    // Verify files exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-recall.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
  });

  it("scaffolds partial selection", () => {
    const results = scaffoldItems(tmpDir, ["hooks", "agents"], DEFAULT_OPTS);
    expect(results).toHaveLength(2);

    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
    // Skills should NOT exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills"))).toBe(false);
  });
});

// =============================================================
// T-4/T-5: --no-wizard and --all flags via handleClaudeCode
// =============================================================
describe("handleClaudeCode with wizard flags", () => {
  let tmpDir: string;
  let origCwd: () => string;
  let origExit: (code?: number) => never;
  let exitCode: number | undefined;

  beforeEach(() => {
    tmpDir = makeTmpDir();
    origCwd = process.cwd;
    process.cwd = () => tmpDir;
    exitCode = undefined;
    origExit = process.exit;
    process.exit = ((code?: number) => {
      exitCode = code;
      throw new Error(`process.exit(${code})`);
    }) as never;
  });

  afterEach(() => {
    process.cwd = origCwd;
    process.exit = origExit;
    cleanTmpDir(tmpDir);
    vi.restoreAllMocks();
  });

  it("--no-wizard does core setup only, no extras (AC-6)", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { handleClaudeCode } = await import("../index");

    const origLog = console.log;
    console.log = () => {};
    try {
      await handleClaudeCode({
        url: "http://localhost:3000",
        apiKey: "test-key",
        workspace: "ws-123",
        noWizard: true,
      });
    } finally {
      console.log = origLog;
    }

    // Core setup files should exist
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, "CLAUDE.md"))).toBe(true);

    // Wizard extras should NOT exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents"))).toBe(false);
  });

  it("--all installs everything without prompting (AC-7)", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { handleClaudeCode } = await import("../index");

    const origLog = console.log;
    let output = "";
    console.log = (...args: unknown[]) => {
      output += args.join(" ") + "\n";
    };

    try {
      await handleClaudeCode({
        url: "http://localhost:3000",
        apiKey: "test-key",
        workspace: "ws-123",
        all: true,
      });
    } finally {
      console.log = origLog;
    }

    // Core setup
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, "CLAUDE.md"))).toBe(true);

    // All extras should exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-recall.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);

    // Output should mention extras
    expect(output).toContain("Extras installed:");
  });
});

// =============================================================
// T-5: CLI flag integration via commander
// =============================================================
describe("CLI flag integration", () => {
  let tmpDir: string;
  let origCwd: () => string;
  let origExit: (code?: number) => never;

  beforeEach(() => {
    tmpDir = makeTmpDir();
    origCwd = process.cwd;
    process.cwd = () => tmpDir;
    origExit = process.exit;
    process.exit = ((code?: number) => {
      throw new Error(`process.exit(${code})`);
    }) as never;
  });

  afterEach(() => {
    process.cwd = origCwd;
    process.exit = origExit;
    cleanTmpDir(tmpDir);
    vi.restoreAllMocks();
  });

  it("--no-wizard flag is recognized by commander", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { Command } = await import("commander");
    const { registerConnectCommand } = await import("../index");

    const program = new Command();
    program.exitOverride();
    registerConnectCommand(program);

    const origLog = console.log;
    console.log = () => {};
    try {
      await program.parseAsync([
        "node", "mnotes", "connect", "claude-code",
        "--url", "http://localhost:3000",
        "--api-key", "test-key",
        "--workspace", "ws-123",
        "--no-wizard",
      ]);
    } finally {
      console.log = origLog;
    }

    // Only core files, no extras
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(false);
  });

  it("--all flag is recognized by commander", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { Command } = await import("commander");
    const { registerConnectCommand } = await import("../index");

    const program = new Command();
    program.exitOverride();
    registerConnectCommand(program);

    const origLog = console.log;
    console.log = () => {};
    try {
      await program.parseAsync([
        "node", "mnotes", "connect", "claude-code",
        "--url", "http://localhost:3000",
        "--api-key", "test-key",
        "--workspace", "ws-123",
        "--all",
      ]);
    } finally {
      console.log = origLog;
    }

    // All extras should exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
  });
});
