import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import {
  scaffoldItems,
  ALL_WIZARD_ITEMS,
  WIZARD_CHOICES,
} from "../wizard";
import type { WizardItem } from "../wizard";
import { generateHooksTemplate, generateHookScripts, HOOKS_HEADER } from "../../../templates/claude-code/hooks";
import { generateSkillTemplates } from "../../../templates/claude-code/skills";
import { generateAgentTemplates } from "../../../templates/claude-code/agents";

// Mock createClient so resolveWorkspace can validate workspaces without a real server
vi.mock("../../../client", () => ({
  createClient: () => ({
    listWorkspaces: async () => ({
      data: [
        { id: "ws-123", name: "Test", slug: "test-123", isDefault: true },
      ],
    }),
    createWorkspace: async (name: string) => ({
      data: { id: name, name, slug: name, isDefault: false },
    }),
  }),
}));

function makeTmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "mnotes-wizard-test-"));
}

function cleanTmpDir(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

const DEFAULT_OPTS = {
  url: "http://localhost:3000",
  workspaceId: "ws-test-123",
};

// =============================================================
// T-1: Template generation — hooks
// =============================================================
describe("hooks template", () => {
  it("generates SessionStart hook referencing global bash script path", () => {
    const hooks = generateHooksTemplate(DEFAULT_OPTS);
    expect(hooks.SessionStart).toBeDefined();
    expect(hooks.SessionStart).toHaveLength(1);
    expect(hooks.SessionStart![0].matcher).toBe("");
    expect(hooks.SessionStart![0].hooks).toHaveLength(1);
    expect(hooks.SessionStart![0].hooks[0].type).toBe("command");
    // Global path — resolves at generation time via os.homedir(), with workspaceId argument
    const cmd = hooks.SessionStart![0].hooks[0].command;
    expect(cmd).toContain(
      path.join(".claude", "hooks", "mnotes", "scripts", "mnotes-session-start.sh")
    );
    expect(cmd).toContain(DEFAULT_OPTS.workspaceId);
    // The script path portion (before the space + argument) is absolute
    expect(path.isAbsolute(cmd.split(" ")[0])).toBe(true);
  });

  it("generates hook scripts targeting v1 endpoints with workspaceId arg and Accept header", () => {
    const scripts = generateHookScripts(DEFAULT_OPTS);
    expect(scripts).toHaveLength(2);

    const startScript = scripts.find((s) => s.filename === "mnotes-session-start.sh")!;
    expect(startScript.content).toContain("localhost:3000/api/v1/composites/project-context-load");
    expect(startScript.content).not.toContain("/api/mcp");
    // workspaceId is a runtime argument, not hardcoded
    expect(startScript.content).toContain("WORKSPACE_ID=");
    expect(startScript.content).not.toContain("ws-test-123");
    expect(startScript.content).toContain('Accept: application/json');

    const stopScript = scripts.find((s) => s.filename === "mnotes-session-stop.sh")!;
    expect(stopScript.content).toContain("localhost:3000/api/v1/sessions/log");
    expect(stopScript.content).not.toContain("/api/mcp");
  });

  it("strips trailing slashes from URL in hook scripts", () => {
    const scripts = generateHookScripts({ url: "http://example.com///", workspaceId: "ws-1" });
    const startScript = scripts.find((s) => s.filename === "mnotes-session-start.sh")!;
    expect(startScript.content).toContain("http://example.com/api/v1/composites/project-context-load");
    expect(startScript.content).not.toContain("///");
  });
});

// =============================================================
// T-1: Template generation — skills
// =============================================================
describe("skills templates", () => {
  it("generates two skill files", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    expect(skills).toHaveLength(2);
  });

  it("generates store and recall skills as SKILL.md inside their own folder (AC-1)", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    const paths = skills.map((s) => s.path);
    expect(paths).toContain("mnotes-store/SKILL.md");
    expect(paths).toContain("mnotes-recall/SKILL.md");
  });

  it("includes m-notes generated header (AC-8)", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("Generated by m-notes CLI");
    }
  });

  it("includes workspaceId in skill content", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("ws-test-123");
    }
  });

  it("includes frontmatter with name and description and omits non-standard fields", () => {
    const skills = generateSkillTemplates(DEFAULT_OPTS);
    for (const skill of skills) {
      expect(skill.content).toContain("---");
      expect(skill.content).toContain("name:");
      expect(skill.content).toContain("description:");
      expect(skill.content).not.toMatch(/^trigger:/m);
    }
  });
});

// =============================================================
// T-1: Template generation — agents
// =============================================================
describe("agents templates", () => {
  it("generates one agent file", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents).toHaveLength(1);
  });

  it("generates knowledge-manager agent", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].filename).toBe("knowledge-manager.md");
  });

  it("includes m-notes generated header (AC-8)", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    for (const agent of agents) {
      expect(agent.content).toContain("Generated by m-notes CLI");
    }
  });

  it("includes workspaceId in agent content", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].content).toContain("ws-test-123");
  });

  it("includes frontmatter with name and description", () => {
    const agents = generateAgentTemplates(DEFAULT_OPTS);
    expect(agents[0].content).toContain("---");
    expect(agents[0].content).toContain("name: knowledge-manager");
    expect(agents[0].content).toContain("description:");
  });
});

// =============================================================
// T-2: Wizard choices structure
// =============================================================
describe("wizard choices", () => {
  it("has three items: hooks, skills, agents", () => {
    expect(ALL_WIZARD_ITEMS).toEqual(["hooks", "skills", "agents"]);
  });

  it("each choice has value, label, and description", () => {
    for (const choice of WIZARD_CHOICES) {
      expect(choice.value).toBeTruthy();
      expect(choice.label).toBeTruthy();
      expect(choice.description).toBeTruthy();
    }
  });
});

// =============================================================
// T-3: scaffoldItems — hooks
// =============================================================
describe("scaffoldItems: hooks", () => {
  let tmpDir: string;
  let fakeHome: string;
  let origHome: string | undefined;

  beforeEach(() => {
    tmpDir = makeTmpDir();
    fakeHome = makeTmpDir();
    origHome = process.env.HOME;
    process.env.HOME = fakeHome;
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
    cleanTmpDir(fakeHome);
    if (origHome === undefined) delete process.env.HOME;
    else process.env.HOME = origHome;
  });

  it("writes scripts to global ~/.claude/hooks/mnotes/scripts/ and settings.json to project (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("hooks");
    // 2 bash scripts + settings.json
    expect(results[0].filesWritten).toHaveLength(3);

    // settings.json is project-local
    const settingsPath = path.join(tmpDir, ".claude", "settings.json");
    expect(fs.existsSync(settingsPath)).toBe(true);

    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    expect(settings.hooks).toBeDefined();
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(settings.hooks.SessionStart).toHaveLength(1);

    // Bash scripts live under fake HOME at ~/.claude/hooks/mnotes/scripts/
    const globalScriptsDir = path.join(fakeHome, ".claude", "hooks", "mnotes", "scripts");
    const startScript = path.join(globalScriptsDir, "mnotes-session-start.sh");
    const stopScript = path.join(globalScriptsDir, "mnotes-session-stop.sh");
    expect(fs.existsSync(startScript)).toBe(true);
    expect(fs.existsSync(stopScript)).toBe(true);

    // Project directory must NOT contain scripts
    expect(fs.existsSync(path.join(tmpDir, ".claude", "hooks"))).toBe(false);

    // settings.json references the global absolute path with workspaceId argument
    expect(settings.hooks.SessionStart[0].hooks[0].command).toBe(`${startScript} ${DEFAULT_OPTS.workspaceId}`);

    const startContent = fs.readFileSync(startScript, "utf-8");
    expect(startContent).toContain("Accept: application/json");
    expect(startContent).toContain("/api/v1/composites/project-context-load");
  });

  it("merges hooks into existing settings.json (AC-5)", () => {
    const claudeDir = path.join(tmpDir, ".claude");
    fs.mkdirSync(claudeDir, { recursive: true });

    const existingSettings = {
      permissions: { allow: ["Read"] },
      hooks: {
        PreToolUse: [{ type: "command", command: "echo pre-tool" }],
      },
    };
    fs.writeFileSync(
      path.join(claudeDir, "settings.json"),
      JSON.stringify(existingSettings, null, 2),
      "utf-8"
    );

    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);

    const settings = JSON.parse(
      fs.readFileSync(path.join(claudeDir, "settings.json"), "utf-8")
    );

    // Existing settings preserved
    expect(settings.permissions.allow).toEqual(["Read"]);
    // Existing hooks preserved
    expect(settings.hooks.PreToolUse).toHaveLength(1);
    expect(settings.hooks.PreToolUse[0].command).toBe("echo pre-tool");
    // New hooks added
    expect(settings.hooks.SessionStart).toHaveLength(1);
  });

  it("does not duplicate hooks on re-run (AC-5)", () => {
    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);
    scaffoldItems(tmpDir, ["hooks"], DEFAULT_OPTS);

    const settings = JSON.parse(
      fs.readFileSync(path.join(tmpDir, ".claude", "settings.json"), "utf-8")
    );

    expect(settings.hooks.SessionStart).toHaveLength(1);
  });
});

// =============================================================
// T-3: scaffoldItems — skills
// =============================================================
describe("scaffoldItems: skills", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("creates skill files as .claude/skills/<name>/SKILL.md (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("skills");
    expect(results[0].filesWritten.length).toBeGreaterThan(0);

    const skillsDir = path.join(tmpDir, ".claude", "skills");
    expect(fs.existsSync(path.join(skillsDir, "mnotes-store", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(skillsDir, "mnotes-recall", "SKILL.md"))).toBe(true);
  });

  it("generated skill files include header (AC-8)", () => {
    scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    const storeContent = fs.readFileSync(
      path.join(tmpDir, ".claude", "skills", "mnotes-store", "SKILL.md"),
      "utf-8"
    );
    expect(storeContent).toContain("Generated by m-notes CLI");
  });

  it("preserves user-created skill files (AC-5)", () => {
    const storeDir = path.join(tmpDir, ".claude", "skills", "mnotes-store");
    fs.mkdirSync(storeDir, { recursive: true });

    // Write a user-created file at the same path
    fs.writeFileSync(
      path.join(storeDir, "SKILL.md"),
      "# My custom store skill\nCustom content here",
      "utf-8"
    );

    scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    // The user file should be preserved
    const content = fs.readFileSync(path.join(storeDir, "SKILL.md"), "utf-8");
    expect(content).toContain("My custom store skill");
    expect(content).not.toContain("Generated by m-notes CLI");

    // The recall skill should still be written (new file)
    expect(
      fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-recall", "SKILL.md"))
    ).toBe(true);
  });

  it("overwrites m-notes generated skill files on re-run (AC-5)", () => {
    scaffoldItems(tmpDir, ["skills"], DEFAULT_OPTS);

    // Re-run with different workspaceId
    scaffoldItems(tmpDir, ["skills"], { url: "http://new-url.com", workspaceId: "ws-new" });

    const content = fs.readFileSync(
      path.join(tmpDir, ".claude", "skills", "mnotes-store", "SKILL.md"),
      "utf-8"
    );
    expect(content).toContain("ws-new");
  });
});

// =============================================================
// T-3: scaffoldItems — agents
// =============================================================
describe("scaffoldItems: agents", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("creates agent files in .claude/agents/ (AC-4)", () => {
    const results = scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);
    expect(results).toHaveLength(1);
    expect(results[0].item).toBe("agents");
    expect(results[0].filesWritten.length).toBeGreaterThan(0);

    expect(
      fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))
    ).toBe(true);
  });

  it("generated agent files include header (AC-8)", () => {
    scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);

    const content = fs.readFileSync(
      path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"),
      "utf-8"
    );
    expect(content).toContain("Generated by m-notes CLI");
  });

  it("preserves user-created agent files (AC-5)", () => {
    const agentsDir = path.join(tmpDir, ".claude", "agents");
    fs.mkdirSync(agentsDir, { recursive: true });

    fs.writeFileSync(
      path.join(agentsDir, "knowledge-manager.md"),
      "# My custom agent\nCustom agent content",
      "utf-8"
    );

    scaffoldItems(tmpDir, ["agents"], DEFAULT_OPTS);

    const content = fs.readFileSync(
      path.join(agentsDir, "knowledge-manager.md"),
      "utf-8"
    );
    expect(content).toContain("My custom agent");
  });
});

// =============================================================
// T-3: scaffoldItems — all items at once
// =============================================================
describe("scaffoldItems: all items", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTmpDir();
  });

  afterEach(() => {
    cleanTmpDir(tmpDir);
  });

  it("scaffolds hooks, skills, and agents when all selected (AC-7)", () => {
    const results = scaffoldItems(tmpDir, ALL_WIZARD_ITEMS, DEFAULT_OPTS);
    expect(results).toHaveLength(3);

    const items = results.map((r) => r.item);
    expect(items).toContain("hooks");
    expect(items).toContain("skills");
    expect(items).toContain("agents");

    // Verify files exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-recall", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
  });

  it("scaffolds partial selection", () => {
    const results = scaffoldItems(tmpDir, ["hooks", "agents"], DEFAULT_OPTS);
    expect(results).toHaveLength(2);

    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
    // Skills should NOT exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills"))).toBe(false);
  });
});

// =============================================================
// T-4/T-5: --no-wizard and --all flags via handleClaudeCode
// =============================================================
describe("handleClaudeCode with wizard flags", () => {
  let tmpDir: string;
  let fakeHome: string;
  let origHome: string | undefined;
  let origCwd: () => string;
  let origExit: (code?: number) => never;
  let exitCode: number | undefined;

  beforeEach(() => {
    tmpDir = makeTmpDir();
    fakeHome = makeTmpDir();
    origHome = process.env.HOME;
    process.env.HOME = fakeHome;
    origCwd = process.cwd;
    process.cwd = () => tmpDir;
    exitCode = undefined;
    origExit = process.exit;
    process.exit = ((code?: number) => {
      exitCode = code;
      throw new Error(`process.exit(${code})`);
    }) as never;
  });

  afterEach(() => {
    process.cwd = origCwd;
    process.exit = origExit;
    cleanTmpDir(tmpDir);
    cleanTmpDir(fakeHome);
    if (origHome === undefined) delete process.env.HOME;
    else process.env.HOME = origHome;
    vi.restoreAllMocks();
  });

  it("--no-wizard does core setup only, no extras (AC-6)", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { handleClaudeCode } = await import("../index");

    const origLog = console.log;
    console.log = () => {};
    try {
      await handleClaudeCode({
        url: "http://localhost:3000",
        apiKey: "test-key",
        workspace: "ws-123",
        noWizard: true,
      });
    } finally {
      console.log = origLog;
    }

    // Core setup file (CLAUDE.md) should exist; .mcp.json must NOT (#594, #777)
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, "CLAUDE.md"))).toBe(true);

    // Wizard extras should NOT exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents"))).toBe(false);
  });

  it("--all installs everything without prompting (AC-7)", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { handleClaudeCode } = await import("../index");

    const origLog = console.log;
    let output = "";
    console.log = (...args: unknown[]) => {
      output += args.join(" ") + "\n";
    };

    try {
      await handleClaudeCode({
        url: "http://localhost:3000",
        apiKey: "test-key",
        workspace: "ws-123",
        all: true,
      });
    } finally {
      console.log = origLog;
    }

    // Core setup — CLAUDE.md only; .mcp.json must NOT be written (#594, #777)
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, "CLAUDE.md"))).toBe(true);

    // All extras should exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-recall", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);

    // Output should mention extras
    expect(output).toContain("Extras installed:");
  });
});

// =============================================================
// T-5: CLI flag integration via commander
// =============================================================
describe("CLI flag integration", () => {
  let tmpDir: string;
  let fakeHome: string;
  let origHome: string | undefined;
  let origCwd: () => string;
  let origExit: (code?: number) => never;

  beforeEach(() => {
    tmpDir = makeTmpDir();
    fakeHome = makeTmpDir();
    origHome = process.env.HOME;
    process.env.HOME = fakeHome;
    origCwd = process.cwd;
    process.cwd = () => tmpDir;
    origExit = process.exit;
    process.exit = ((code?: number) => {
      throw new Error(`process.exit(${code})`);
    }) as never;
  });

  afterEach(() => {
    process.cwd = origCwd;
    process.exit = origExit;
    cleanTmpDir(tmpDir);
    cleanTmpDir(fakeHome);
    if (origHome === undefined) delete process.env.HOME;
    else process.env.HOME = origHome;
    vi.restoreAllMocks();
  });

  it("--no-wizard flag is recognized by commander", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { Command } = await import("commander");
    const { registerConnectCommand } = await import("../index");

    const program = new Command();
    program.exitOverride();
    registerConnectCommand(program);

    const origLog = console.log;
    console.log = () => {};
    try {
      await program.parseAsync([
        "node", "mnotes", "connect", "claude-code",
        "--url", "http://localhost:3000",
        "--api-key", "test-key",
        "--workspace", "ws-123",
        "--no-wizard",
      ]);
    } finally {
      console.log = origLog;
    }

    // Only CLAUDE.md (core), no .mcp.json (#594, #777), no wizard extras
    expect(fs.existsSync(path.join(tmpDir, "CLAUDE.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".mcp.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(false);
  });

  it("--all flag is recognized by commander", async () => {
    const configUtils = await import("../config-utils");
    vi.spyOn(configUtils, "validateConnection").mockResolvedValue({ ok: true });

    const { Command } = await import("commander");
    const { registerConnectCommand } = await import("../index");

    const program = new Command();
    program.exitOverride();
    registerConnectCommand(program);

    const origLog = console.log;
    console.log = () => {};
    try {
      await program.parseAsync([
        "node", "mnotes", "connect", "claude-code",
        "--url", "http://localhost:3000",
        "--api-key", "test-key",
        "--workspace", "ws-123",
        "--all",
      ]);
    } finally {
      console.log = origLog;
    }

    // All extras should exist
    expect(fs.existsSync(path.join(tmpDir, ".claude", "settings.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "skills", "mnotes-store", "SKILL.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".claude", "agents", "knowledge-manager.md"))).toBe(true);
  });
});
